package com.atakancoban.orm;
// Generated Aug 24, 2017 3:28:08 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ZzAtakanPerson generated by hbm2java
 */
@Entity
@Table(name = "ZZ_ATAKAN_PERSON", schema = "FCBSADM")
public class ZzAtakanPerson implements java.io.Serializable {

	private BigDecimal personId;
	private String lastname;
	private String firstname;
	private String address;
	private String city;
	private String job;

	public ZzAtakanPerson() {
	}

	public ZzAtakanPerson(BigDecimal personId) {
		this.personId = personId;
	}

	public ZzAtakanPerson(BigDecimal personId, String lastname, String firstname, String address, String city,
			String job) {
		this.personId = personId;
		this.lastname = lastname;
		this.firstname = firstname;
		this.address = address;
		this.city = city;
		this.job = job;
	}

	@Id

	@Column(name = "PERSON_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPersonId() {
		return this.personId;
	}

	public void setPersonId(BigDecimal personId) {
		this.personId = personId;
	}

	@Column(name = "LASTNAME", length = 30)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "FIRSTNAME", length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "JOB", length = 100)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

}
